### ISSUE TITLE
[enhancement] Προβολή πίνακα απευθείας από την ιστοσελίδα

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#10]
Υπάρχουν πολλές βιβλιοθήκες για να κάνεις κάτι τέτοιο και δεν νομίζω ότι θα είναι πολύ δύσκολο. Τσέκαρε εδώ: https://jspreadsheets.com/

Προσωπικά αυτό το θεωρώ πολύ σημαντικό feature για να μπαίνει ο άλλος από το κινητό του. Ποιος κάθεται να κατεβάζει κτλ...

**Comment by pmav99** [comment]
Βασικά τώρα που το σκέφτομαι παίζει να μπορείς να κάνεις απευθείας μετατροπή του `*.xls` σε `html`.

Αν θες να δεις ένα παράδειγμα application που είχα κάνει και είναι πολύ παρόμοιο με το δικό σου είναι αυτό: http://craneloads-pmav99.rhcloud.com/ (βάλε έναν αριθμό στα fields χωρίς defaults για να τρέξει).

**Comment by pmav99** [comment]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_html.html
http://stackoverflow.com/questions/32430009/python-pandas-data-frame-save-as-html-page

**Comment by fkaralis** [comment]
Είναι στα to-do Ναι

**Comment by pmav99** [comment]
1. Προσωπικά θα το έκανα πρώτη προτεραιότητα
2. Άμα γράφεις από το κινητό να θυμάσαι να σβήνεις τα quotes γιατί εμφανίζονται διάφορα άχρηστα στα messages σου.

**Comment by pmav99** [comment]
Μην το κλείνεις. 

1. Όταν o πίνακας είναι `*.xls`, δεν δουλεύει. Πετάει ένα exception σχετικό με το gzip
2. Όταν ο πίνακας είναι πολύ μεγάλος γίνεται πολύ αργό (τουλάχιστον για τον server του flask)
3. Όταν ο πίνακας είναι πολύ μεγάλος το UI φαντάζομαι ότι θα γίνεται αισχρό στα κινητά κτλ. 

Για λύση στα 2 και 3, βάλε pagination ή ακόμα καλύτερα ζήτα με μία φόρμα να σου δίνουν τα πρώτα γράμματα του επιθέτου και να εμφανίζεις μόνο τα επίθετα που ξεκινούν με αυτά (πχ `Κ` ή `ΚΑ` για να εμφανίστεί το δικό σου). Καλό είναι να υπάρχει η δυνατότητα να αλλάζει το αρχεικό γράμμα του επιθέτου στη σελίδα προβολής του πίνακα. Ακόμα καλύτερο θα είναι αν το κάνεις με AJAX

**Comment by fkaralis** [comment]
1. Έχουν αλλάξει τα data (συμπιεσμένα) και η βάση

**Comment by fkaralis** [comment]
2-3. 
Με flask pagination θα φορτώνονται οι επόμενες πχ 50 εγγραφές κάθε φορά; Δεν ξέρω αν κερδίζει κάτι κάποιος που θα θέλει να βρει πχ το νο 2000. Η λύση της αποκλειστικής εύρεσης εγγραφής στερεί τη θέαση της εγγραφής στη θέση της μέσα στον πίνακα (χρησιμεύει για διάφορους λόγους πχ συγκρίσεις με πάνω-κάτω κλπ). 

Χρησιμοποιώ [DataTables](https://datatables.net/) νομίζω κάτι κάνουν ειδικά για το (3), αλλά και για το (2) μετά την όποια αναμονή έχεις και pagination και Αναζήτηση

**Comment by pmav99** [comment]
Όχι μια χαρά είναι το DataTables. Τώρα που έβαλα τα νέα δεδομένα μια χαρά.
