### ISSUE TITLE
Save emails on database

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#11]
όταν κάποιος δίνει τα στοιχεία του στο view εγγραφή, η εφαρμογή προσπαθεί να στείλει ένα email στον admin. Εν γένει δεν είναι πολύ καλό αυτό. Άμα σε κάνει στόχο κανένα bot, θα κάνει flood στο email σου για πλάκα.

Μια πιο λογική αντιμετώπιση θα ήταν να σώζεις τα email στη βάση δεδομένων και όταν έρθει η ώρα της έκδοσης νέου πίνακα να τα διαβάζεις από εκεί.

**Comment by pmav99** [comment]
Άκυρο. Τελικά δεν στέλνεις email στον admin. Απλά χρειάζεσαι τα credentials του admin για να στείλεις το email

**Comment by fkaralis** [comment]
Ναι η εγγραφή γίνεται Έτσι κι αλλιώςείναι ένα από τα πράγματα που θέλω, Πώς δηλαδή περνάς τα στοιχεία mail username password και admin όταν είναι live. (εδώ τα βάζω χειρονακτικά)
