### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#12]
Δεν θα ήταν άσχημο να έχεις και δύο λόγια σχετικά με το τι είναι η σελίδα και το τι μπορεί να κάνει. Λίγα λόγια όμως γιατί δεν θες να χάσεις τη φόρμα από την εμφάνιση στα κινητά κτλ

**Comment by fkaralis** [comment]
Done 96e3c1fa2a71ff61cae3378f33b5f88c511a127d

**Comment by pmav99** [comment]
Πολύ καλύτερα!

Να δίνεις λίγο περισσότερη προσοχή στα commit messages. To `sm and xs templates fix` δεν περιγράφει το τι έκανε το `96e3c1f`
