### ISSUE TITLE
Stop storing data in the repository

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#2]
It is usually a good idea not to store data in the repo. You might store some data if they are being used for testing but you usually avoid to store everything on .git. Data should be stored via other means (e.g. databases). If somebody needs the data, he can run the script and download them himself.

For now, just answer the following two questions:
1. How can you remove the data from the repo? Are there any downsides?
2. Can you remove the data from the git history? Are there any gotchas that you need to know about?

**Comment by fkaralis** [comment]
Done
Involved:
[.gitignore
](https://github.com/fkaralis/talaiporosanaplirotis/blob/master/.gitignore)https://rtyley.github.io/bfg-repo-cleaner/
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by pmav99** [comment]
Kudos
