### ISSUE TITLE
Reduce data size

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#22]
Δοκίμασε να κάνεις τα εξής:

1. Export των δεδομένων από τα αρχεία `xls` και `html` σε `CSV`
2. Gzip των `csv`
3. Σύγκριση του όγκου των δεδομένων με τον υφιστάμενο

Αν μειώνεται και άλλο ο όγκος των δεδομένων (που νομίζω ότι θα γίνει), τότε να ξέρεις ότι πιθανά να σε παιρνει να κάνεις και απλά τo φάκελο data κατευθείαν commit στο git.

Μπορείς να δοκιμάσεις τη συμπίεση και με 7z/xy/bzip που λογικά θα δίνουν ακόμα ελαφρά υψηλότερα compression ratios

**Comment by fkaralis** [comment]
Όντως μειώνεται 4 με 5 φορές το μέγεθος. Αλλά βάζουμε data στο git ??

**Comment by pmav99** [comment]
κανονικά όχι, αλλά θυμίσου το zen of python:
```
python -c 'import this' | grep 'rules\|practicality'
```

**Comment by fkaralis** [comment]
Μια λύση είναι και το private repo.?

**Comment by pmav99** [comment]
Το ζήτημα εδώ δεν είναι το private ή το public.

Dynamic data (πχ users, their photos, their profile descriptions κτλ) ναι δεν βάζεις στο repo. Τα βάζεις στη βάση δεδομένων. Εδώ όμως μιλάς για static data. Κάθε πίνακας που εκδίδεται δεν αλλάζει. Κάθε φορά που βγαίνει ένας νέος, απλά κάνεις ένα νέο commit.

Ναι και πάλι δεν είναι το καλύτερο να τα βάλεις στο repo, αλλά αν σε διευκολύνει πχ στο deployment τότε δεν βλέπω και γιατί όχι. Αλλά και πάλι πρέπει να δεις το ζήτημα του χώρου. Αν το repo καταλήξει να είναι 1 GB τότε σίγουρα δεν είναι καλή λύση. Αλλά αν μιλάμε πχ για 100ΜΒ σύνολο + 20-30ΜΒ ανά έτος κλάιν.

**Comment by fkaralis** [comment]
το μέγεθος πλέον έχει κατέβει στα 250ΜΒ, για όλα τα 14 έτη.

**Comment by pmav99** [comment]
Good. Αν τα κάνεις λοιπόν και ένα `*.csv.gz` θα γίνουν γύρω στα 50MB και δεν θα έχεις κανένα πρόβλημα. Και αν αποφασίσεις στο μέλλον να τα πετάξεις σε μια βάση δεδομένων η διαδικασία θα είναι trivial.

Άντε, παρακάλεμα θες μου φαίνεται... Τόση ώρα που το μελετάμε θα το είχες γράψει το script...

**Comment by fkaralis** [comment]
ως csv.gz είναι το μέγεθος :)

το πριβε το ανέφερα γιατί είχα την εντύπωση ότι δεν είναι μόνο θέμα χώρου αλλά και "προστασίας" δεδομένων; Εξάλλου τα δεδομένα και η βάση είναι ουσιαστικά το αποτέλεσμα της περισσότερης δουλειάς, έτσι χύμα να τα έχω;

**Comment by pmav99** [comment]
Το αν θες να τα έχεις ανοικτά ή κλειστά είναι άλλη συζήτηση. Αν τα έχεις κάνει πάντως σαν CSV, στείλε μου τα και κάνε push και τον κώδικα που δουλεύει με αυτά για να τα βάλω στο openshift

**Comment by fkaralis** [comment]
yes, once proofed checked

**Comment by pmav99** [comment]
Βασικά αν αποφασίσεις ότι θα τα κρατήσεις σαν `csv.gz` και ότι θα τα κάνεις commit, κάνε τα κατευθείαν commit.

**Comment by fkaralis** [comment]
good old scp
