### ISSUE TITLE
Που είναι οι θεολόγοι οέο;

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#23]
Ζητάω θεολόγους και μου βγάζει μουσικούς. Λογικά είναι λάθος στην sqlite.
![θεολόγοι](http://storage7.static.itmages.com/i/17/0403/h_1491240630_5267502_51732d81a6.png)

**Comment by fkaralis** [comment]
Όχι επρόκειτο για λάθος στο χτίσιμο του query στις main._get_fields και
main._update_fields στο views.py

Το πρόβλημα είναι ότι εφόσον πολλοί πίνακες έχουν >1 κλάδους, το πεδίο
klados_id στον pinakas (που έχει όλους τους πίνακες) είναι VARCHAR με μορφή
'κλάδος( κλαδος)*'. Πχ πολλοί πίνακες πληροφορικής έχουν klados_id == '113
112' που αντιστοιχούν στους ΠΕ19 (ΑΕΙ) και ΠΕ20 (ΤΕΙ).

Έτσι λοιπόν στα queries το φιλτράρισμο για τον κλάδο γινόταν με 'LIKE',
αντί για '=' και ,αναπόφευκτα, ο πίνακας των Θεολόγων (klados_id == 3),
μπλεκόταν με τους Μουσικούς (35), τους Καλών Τεχνών (13) κ.o.κ.

Στο branch 'query_bug' έκανα ένα πρόχειρο μπάλωμα αλλά θέλει λίγη δουλίτσα ακόμα..

Πάντως ήταν και αφορμή για σουλούπωμα των views, και κατανόηση του
δυναμικού χτισίματος query που απλά το είχα αντιγράψει τότε χωρίς να το
πολυκαταλάβω..

Εν ολίγοις.. My compliments!
