### ISSUE TITLE
Implement proper logging

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#3]
The approach you are using with `globalvars.log.write()` is a total hack... 

Did you copy that from somewhere? If yes where? I would like to get a look at the rationale (and laugh :P). In the meanwhile, get rid of it...

Python has extensive support for logging, but the required library has a significant learning curve. If you are interested in learning it check the following links. If you don't want to lose time with that now (which is probably a good idea) just use `print()`.

https://docs.python.org/3/library/logging.html
https://docs.python.org/3/howto/logging.html#logging-basic-tutorial
https://gist.github.com/pmav99/49c01313db33f3453b22

**Comment by pmav99** [comment]
BTW, chapter 14 in Mastering Object-oriented Python by S.Lott is really good if you want to grasp logging

**Comment by fkaralis** [comment]
Will stop using it from now on. Until further need arises, I'll stick with the 'don't lose time' advice (and print()).
