### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#31]
Βρήκα μια ιταλική εταιρεία hosting που δίνει ένα φτηνό VPS με 1€ το μήνα. Δημιούργησα ένα VPS και θα τεστάρω μία να τρεξω το talaiporosanaplirotis εκεί. Αν πάει καλά, το πετάμε εκεί πάνω και τέλος. 

I will keep you posted.

**Comment by fkaralis** [comment]
Για Aruba ο λόγος (που μου έστειλες;)
Να φτιάξω λογαριασμό; Με το domain που έχω απ'το παπακι τι κάνουμε?

**Comment by pmav99** [comment]
Για τσέκαρε εδώ: http://212.237.15.237:5000/

**Comment by fkaralis** [comment]
nice
(remember latest commit a048dddf4bfb3f381e9258f54db876bff8ec1eba)

**Comment by pmav99** [comment]
Ναι στην Aruba έχει γίνει το deployment αλλά δεν έχω βάλει το τελευταίο commit. 

Anyway. Αν το VPΝ που δίνουν με το 1.24€/μήνα σηκώνει την εφαρμογή σου (που λογικά θα το κάνει, ιδίως αν βάλουμε και κανένα caching) είναι πολύ καλή προσφορά. Θα σου κοστίζει 1.24 * 12 = 15€ το χρόνο και θα σου δώσει την ευκαιρία να μάθεις ένα σωρό πράγματα.

Επειδή χρησιμοποιούμε docker για το deployment θέλω να κάνεις σε πρώτη φάση τα εξής:

1. Εγγραφή στην aruba. Πάτα στο κουμπί "Request trial" θα σου στείλουν εντός 24 ώρων voucher για 2 μήνες δωρεάν.
2. Εγγραφή στο docker hub: https://hub.docker.com/
3. Ρίξε λίγο διάβασμα για docker ξεκινώντας από εδώ: https://docs.docker.com/learn/
4. Ρίξε περισσότερο διάβασμα για docker (έχεις δουλειά να κάνεις) θα σου στείλω μήνυμα στο signal με λεπτομέρειες.

**Comment by fkaralis** [comment]
Εντάξει με την Aruba αλλά πού είναι αυτά για το VPN?

Το Docker δεν υποστηρίζει τον 32bit μου. Έχω εγκαταστήσει μια ανεπίσημη έκδοση αλλά δεν μπορώ να κάνω κανένα tutorial, ούτε το μάθημα από το udemy.. Μια εβδομάδα τώρα το ψάχνω έχω αρχίσει να το βλέπω στον ύπνο μου. Μέχρι να πάρω καινούριο μηχάνημα, λέω να προχωρήσω με την εφαρμογή.

**Comment by pmav99** [comment]
Sorry. Ορθογραφικό λάθος. όπου VPN διάβασε VPS

Έχεις 32 bit επεξεργαστή ή 32 bit λειτουργικό; Εκτός και αν ο επεξεργαστής σου είναι 15ετίας, είναι μάλλον απίθανο να μην είναι 64bit. Αν έχεις 32 bit λειτουργικό, τότε με νέα εγκατάσταση βάλε 64bit. 2017 έχουμε...

**Comment by fkaralis** [comment]
*choke* ναι 64bit είναι ο επεξεργαστής. οκ i'll be back με νεώτερα..
