### ISSUE TITLE
Get rid of globalvars

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#4]
Get rid of global variables. They do occasionally have their use cases but at your level you should just avoid them. 

Restructure your code so that `globalvars.py` is not needed any more (without losing functionality!)

**Comment by fkaralis** [comment]
Done

**Comment by pmav99** [comment]
Done???
You are still using global variables... I was not talking about the name of the module...

**Comment by fkaralis** [comment]
Thought not declaring them as global and having them as module-scope would do

**Comment by fkaralis** [comment]
Went object-oriented! Faster too..
https://github.com/fkaralis/talaiporosanaplirotis/commit/53bc76afa5f257fe89fbdf453f4b01f10a494216
