### ISSUE TITLE
Create/use a wiki instead of log.txt

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#5]
`log.txt` is really a most unsuitable name for practically everything...

They way you should be keeping notes is a wiki. 

If the notes are project related you can use Github's wiki. 
If the notes are more general you should probably use a dedicated repository just for the wiki.

If you need private access to the wiki, which is probably a good idea for general wikis, you can use gitlab or bitbucket which both offer private projects for free (gitlab is probably a better solution).

If you want to have local access to the wiki (which can also be an idea - e.g. offline access) you can use [gollum](https://github.com/gollum/gollum).

If you are interested in trying gollum (which I totally recommend) ask me for installation instructions because what they are suggesting in the readme is totally wrong IMHO.

**Comment by fkaralis** [comment]
Tried gollum as suggested a while ago, didn't get past installation. Instructions welcome.

**Comment by pmav99** [comment]
The ruby equivalent of virtualenv is [`rvm`](https://rvm.io/) and [`bundler`](http://bundler.io/). The former is being used for choosing the appropriate ruby version and the latter for pinning package versions.

You don't need rvm, but you definitely want to use bundler.
1. Make sure ruby is installed: `sudo apt-get install ruby`
2. Install bundler in the global ruby installation: `sudo apt-get install bundler`
3. Now that you have bundler installed create a new directory: `mkdir /path/to/wiki`
4. Enter the new directory: `cd /path/to/wiki`
5. Initialize a new git repo: `git init`
6. Add a suitable [`.gitignore`](https://github.com/github/gitignore/blob/master/Ruby.gitignore).
7. Create a file called `Gemfile` with the following contents and add it to the repo:
   
   ``` ruby
   source 'https://rubygems.org'
   gem 'gollum'
   ```
   
   and `git add ./Gemfile && git commit -m 'Add Gemfile'.`
8. Install gollum using bundler: `bundler install --path .bundle  --binstubs`
9. This command installed `gollum`'s dependencies in a subdirectory called `.bundle` and the `gollum` executable in a subdirectory called `bin`. Add `bin` to the `.gitignore`. `.bundle` is already there.
10. You can start gollum by executing: `./bin/gollum`
11. Visit `http://localhost:4567/Home`
12. Start taking notes!

**Comment by fkaralis** [comment]
Will keep this info for future use. Started Github wiki

**Comment by pmav99** [comment]
Note: Usually changelogs are written in reverse order, i.e. the most recent entries are at the top. It is usually more convenient this way.
