### ISSUE TITLE
Remove `.pydevproject` and `.project`

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#6]
Why files that are related to your own IDE choice need to be in the repository? Are you the only working on the codebase? Or, perhaps, you are presuming that we should be using the same editor as you? :package: 

Get rid of them!

**Comment by fkaralis** [comment]
Done. Do I need to clean history too?

**Comment by pmav99** [comment]
do they make cloning/forking the repository slow?

**Comment by fkaralis** [comment]
Done
