### ISSUE TITLE
Learn how to close issues!

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#7]
When something is done you can close the issue!

Furthermore, when code is involved, you can also close the issue with the commit message:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by fkaralis** [comment]
Understood. But still not always sure wether closure is achieved. (See #4)

**Comment by pmav99** [comment]
In order to close the issue you must write something like the following in the commit message (the braces are not mandatory)

```
Remove globalvariables from blah blah blah

[fixes #7]
```
