### ISSUE TITLE
Stop being sloppy!

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#8]
Why are you doing multiple things in the same commit?
Are you too bored to type?
If yes, then it is time to learn touch typing :P 

Split the following commit message in two (you might need `git push --force`):
https://github.com/fkaralis/talaiporosanaplirotis/commit/ab73c8a1f709ed4dfc2b8f2515cda9759156c6f6

Note: In big projects you would never do that (i.e. change repo history for something as trivial) but it is good practise :P

**Comment by fkaralis** [comment]
Done
