### ISSUE TITLE
Setting up instructions do not work.

### ISSUE THREAD

**Issue by pmav99** [fkaralis/talaiporosanaplirotis#9]
Setting up instructions do not work

There is no `talaiporosanaplirotis.sqlite` in the repo, nor is there a `data` dir. Please write down all the necessary steps to run the code. Creating a new virtualenv and cloning to a new directory will probably help

**Comment by fkaralis** [comment]
Εστάλη από το κινητό Huawei μου------- Αρχικό μήνυμα --------Θέμα: [fkaralis/talaiporosanaplirotis] Setting up instructions do not work. (#9)Από: pmav99 Προς: fkaralis/talaiporosanaplirotis Κοιν.: Subscribed Setting up instructions do not work.
